# NOTE: update this with your service name
service: service-name

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  betUsersTableName: ${self:custom.stage}-beta_users

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment: ${file(env.yml):${self:custom.stage}}

functions:
  hello:
    handler: src/handler.main
    events:
      - http:
          path: hello
          method: get
# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
