Resources:
  BetaUsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.betUsersTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      BillingMode: PAY_PER_REQUEST
